# Generated by Django 5.2.17 on 2026-09-09 07:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_coolfont'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('premium', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preview_url', models.URLField(blank=True)),
                ('text_color', models.CharField(default='#FFFFFFFF', max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a color using # followed by eight hexadecimal characters.', regex='^#[0-9A-Fa-f]{8}$')])),
                ('key_aplha', models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('keyboard_bg', models.URLField()),
                ('normal_key_bg', models.URLField()),
                ('speciality_keys_bg', models.URLField()),
                ('backspace_key_bg', models.URLField(blank=True)),
                ('uppercase_letter_bg', models.URLField(blank=True)),
                ('number_button_bg', models.URLField(blank=True)),
                ('emoji_button_bg', models.URLField(blank=True)),
                ('comma_button_bg', models.URLField(blank=True)),
                ('enter_button_bg', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='catalog.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='catalog.subcategory')),
            ],
            options={
                'verbose_name': 'keyboard',
                'verbose_name_plural': 'keyboards',
            },
        ),
    ]
