# Generated by Django 5.2.17 on 2026-09-09 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_keyboard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyboard',
            options={'ordering': ('priority', '-created_at'), 'verbose_name': 'keyboard', 'verbose_name_plural': 'keyboards'},
        ),
        migrations.RenameField(
            model_name='keyboard',
            old_name='speciality_keys_bg',
            new_name='specialty_keys_bg',
        ),
        migrations.RemoveField(
            model_name='keyboard',
            name='key_aplha',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='key_aipha',
            field=models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
