# Generated by Django 5.2.17 on 2026-09-09 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_keyboard_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyboard',
            name='key_aipha',
        ),
        migrations.AddField(
            model_name='keyboard',
            name='key_alpha',
            field=models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
