# Generated by Django 5.2.17 on 2026-09-09 07:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_wallpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiyEffect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gif_url', models.URLField()),
                ('preview_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('priority', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiyFont',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('font_url', models.URLField()),
            ],
            options={
                'ordering': ('priority', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('transparency', models.FloatField(default=0.85, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'ordering': ('priority', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('transparency', models.FloatField(default=0.9, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('special_key_bg', models.URLField()),
            ],
            options={
                'ordering': ('priority', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DiySound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sound_url', models.URLField()),
                ('preview_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('priority', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('premium', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preview_url', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='catalog.category')),
                ('keyboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='catalog.keyboard')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_items', to='catalog.subcategory')),
                ('wallpaper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='themes', to='catalog.wallpaper')),
            ],
            options={
                'verbose_name': 'theme',
                'verbose_name_plural': 'themes',
                'ordering': ('priority', '-created_at'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThemeIcon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('preview_url', models.URLField(blank=True)),
                ('icon_image', models.URLField()),
                ('alias_id', models.CharField(max_length=255)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='catalog.theme')),
            ],
            options={
                'verbose_name': 'theme icon',
                'verbose_name_plural': 'theme icons',
                'ordering': ('priority', '-created_at'),
            },
        ),
    ]
